# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Introducing Agroecology
description:      'The Basics of Agroecology for Practitioners'
url:              http://trec-agroecology.github.io/introducing-agroecology
baseurl:          /introducing-agroecology
email:            brymz@ufl.edu
feedbackurl:      https://trec.ifas.ufl.edu/agroecology
author:
  name:           'Zack Brym'
  url:            https://trec.ifas.ufl.edu/faculty/brym

github:
  repo:           https://github.com/TREC-Agroecology/introducing-agroecology
  #               Be sure the 'Issues' feature is activated in 'Settings'
